# This is the config file for Light-Dramaturgy

# Adding the theme for minimal.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Light Dramaturgy
description: A PhD by Anthony Arblaster being undertaken at the University of York. Supervised by Dr Katherine Graham and Dr Rebecca Benzie.
