# This is the config file for Light-Dramaturgy

# Adding the theme for minimal.
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Light Dramaturgy
description: A PhD by Anthony Arblaster at the University of York.

# set up the menu
nav:
  - title: Home
    url: /

  - title: About
    url: /about

  - title: Contact
    url: /contact

  - title: Thanks
    url: /thanks
 
# exclude
exclude: 
- READEME.md

footer: Raised on Ngunnawal and Ngambri Country. Made in London. 